# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180516_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='auth',
            new_name='user',
        ),
    ]
